task2
Collapsor7/tspp_shihui pull request #2
Opened 2024-09-27 11:00 UTC by Collapsor7

2024-09-27 14:04 UTC, dimlichmanov requested changes
В остальном решение нравится.

2024-09-27 14:04 UTC, dimlichmanov commented on sem02/concurrent_queue.cpp
> +		cond_full.wait(lock, [this] { return item_count <= 1; });
Здесь не должно быть  item_count < capacity ?

2024-09-27 14:04 UTC, dimlichmanov commented on sem02/concurrent_queue.cpp
> +	private:
В атрибутах всё-таки хочется видеть какую-то реализацию очереди, а не просто отслеживание числа элементов через item_count

2024-09-28 08:31 UTC, Collapsor7 commented on sem02/concurrent_queue.cpp
> +	private:
Здравствуйте! Уже исправила!

2024-09-28 08:32 UTC, Collapsor7 commented on sem02/concurrent_queue.cpp
> +		cond_full.wait(lock, [this] { return item_count <= 1; });
Да, точно, я не заметила

2024-09-28 08:33 UTC, merged

2024-09-28 08:38 UTC, Collapsor7 commented
прости!Я случайно нажала не на ту кнопку!Я объединила ветку

2024-09-30 23:09 UTC, dimlichmanov commented
Задание зачтено. Единственное - хотелось бы видеть размеры тестов побольше.