sem04
Collapsor7/tspp_shihui pull request #5
Opened 2024-10-15 16:24 UTC by Collapsor7

2024-10-16 00:57 UTC, dimlichmanov requested changes
Достаточно сделать только одну версию. Поскольку я начал смотреть AVX, исправляйте её.

2024-10-16 00:57 UTC, dimlichmanov commented on sem04/work4_AVX.cpp
> +                __m256d b = _mm256_loadu_pd(&B[k * N + j]);
Вы умножаете строку А на строку B (поскольку вытаскиваете сразу 4 double). Это неверно.

2024-10-16 00:57 UTC, dimlichmanov commented on sem04/work4_AVX.cpp
> +      for (int i = 0; i < N[i]; i++) {
подумайте, в чём ошибка.

2024-10-21 13:48 UTC, Collapsor7 commented on sem04/work4_AVX.cpp
> +      for (int i = 0; i < N[i]; i++) {
Почему эти три неверны?Является ли следующее суждение неверным?

2024-10-25 14:47 UTC, Collapsor7 commented
Задание 5 было загружено

2024-10-27 06:59 UTC, dimlichmanov requested changes
по 4-ому заданию:
Вы даже в отчёт пишете, что у вас не совпадают результаты, полученные последовательно и параллельно. (Results are incorrect)
Когда я запускал вашу программу, у меня было, по-моему, переполнение стека, так как у вас i отвечает как за номер теста (512, 1024, 2048), так и за номер элемента при проверке результата. Понимаю, что ваш компилятор может это по другому транслировать, но я в этом вижу ошибку. Возможно, результаты не свопадают именно из-за этого
по 5: 
у вас нет ускорения, потому что вы неправильно организовываете работу с rand(). Rand() обращается к некоторому скрытому состосянию, которое является общим для всех потоков. Происходит лишняя синхронизация. Вам нужно использовать отдельный seed для каждого потока и заменить rand() на что-то тпиа rand_r()

2024-10-27 08:25 UTC, Collapsor7 commented
по 4-ому заданию:
Ранее я загрузила неправильный измененный код, а теперь успешно загрузила правильный.Кроме того, отчет также был пересмотрен.
и Задача пятая：
Изменен метод rand_r()

2024-10-27 08:53 UTC, dimlichmanov commented
![изображение](https://github.com/user-attachments/assets/37f93f9b-cf85-4774-92e8-3a31a757963a)
Я не понимаю, что вы кладёте в столбец T. Если предполагать, что T - время, то требуемое ускорение не было получено

2024-10-27 08:58 UTC, dimlichmanov requested changes
4-ую засчитываю

2024-10-28 16:08 UTC, Collapsor7 commented
Я подозреваю, что возникла проблема с указателем памяти, поэтому я заново исправила код.

2024-10-28 17:17 UTC, Collapsor7 commented
задание 6 было отправлено

2024-10-28 17:47 UTC, dimlichmanov requested changes
А что такое P в вашем отчёте для 5-ой задачи? Которое в последнем столбце

2024-10-28 17:47 UTC, dimlichmanov commented on sem05/random_walk.c
> +        unsigned int seed = (unsigned int)time(NULL) ^ omp_get_thread_num();
Лучше оставить просто omp_get_thread_num, ну или если хочется добавить time(), то сделать что-то типа time_global + omp_thread_num(), где time_global - shared переменная, проинициализированная до параллельной секции и гарантированно имеющая одно значение.

2024-10-31 11:35 UTC, dimlichmanov commented
![изображение](https://github.com/user-attachments/assets/57dc92bc-8312-47ce-8b62-741dad59371b)
Как понимать, что результаты оказались неверные?

2024-11-06 17:04 UTC, dimlichmanov commented
![изображение](https://github.com/user-attachments/assets/4e22778e-faab-4a1c-9642-f98b71454552)

2024-11-06 17:04 UTC, dimlichmanov requested changes
5-ое задание сейчас актуально, могу смотреть?

2024-11-06 17:11 UTC, Collapsor7 commented
Я забыл загрузить код измененного задания 6.Затем я сначала загрузил код задачи 5 и все еще дорабатываю отчет

2024-11-06 17:13 UTC, dimlichmanov commented
В итоге, мне сейчас что смотреть можно?

2024-11-06 17:14 UTC, Collapsor7 commented
Задание 6, отчет и код были успешно загружены, задание 5, код

2024-11-06 17:35 UTC, dimlichmanov approved these changes
5-ое и 6-ое зачтены.
1) Чтобы убедиться в корректности работы ещё раз, 5-ое задание запустите на Polus через очередь http://hpc.cmc.msu.ru/node/250. Это обязательно.
2) Закройте Pull Request, сделайте merge в main и новые задания делайте в новой ветке. А то в этот PR попали также ваши задания 03 и 04.

2024-11-06 17:40 UTC, Collapsor7 commented
Уже запущенный на polus, я меняю данные в отчете.Я хочу уточнить, что мое задание 5 было отправлено вовремя.Просто я приехала в Москву всего четыре дня назад, и у меня нет времени его переделывать.

2024-11-06 17:41 UTC, dimlichmanov commented
Отчёт можете не менять)

2024-11-06 17:42 UTC, merged