submit sem07
Collapsor7/tspp_shihui pull request #6
Opened 2024-11-07 11:55 UTC by Collapsor7

submit sem07

2024-11-08 15:55 UTC, dimlichmanov requested changes

2024-11-08 15:55 UTC, dimlichmanov commented on sem07/work7.c
> +            MPI_Isend(local_grid + local_N * N, N, MPI_DOUBLE, rank + 1, 0, MPI_COMM_WORLD, &requests[request_count++]);
Я просил блокирующие.

2024-11-09 15:52 UTC, Collapsor7 commented
Да, я забыла и он был изменен

2024-11-10 16:59 UTC, dimlichmanov requested changes
1) Я не увидел выводов по MPI-P. У вас был сгенерирован файл (об этом символизирует строка Storng MPIP output....), хотелось бы увидеть по нему выводы.

2) Локально текущая версия программы при больших значениях N будет блокироваться. Посмотрите на последний пример семинара и измените вашу программу в соотвтетствии с этим примером.

2024-11-12 11:46 UTC, Collapsor7 commented
Добавлено содержимое файла MPIP, добавлен метод Allreduce и изменен порядок вызова send и recv для предотвращения засорения

2024-11-12 14:29 UTC, dimlichmanov requested changes
Отчёт можете не менять.

2024-11-12 14:29 UTC, dimlichmanov commented on sem07/work7.c
> +        jacobi_update(local_grid, next_grid, local_N, N);
Вы сначала считаете итерацию(jacobi_update), затем обмениваетесь границами между процессами.
Нужно сначала обменяться. Иначе подсчёт некорректен (мы используем данные, не принадлежащие нам)

2024-11-13 10:53 UTC, Collapsor7 commented on sem07/work7.c
> +        jacobi_update(local_grid, next_grid, local_N, N);
понятно

2024-11-13 14:49 UTC, dimlichmanov approved these changes

2024-11-13 17:24 UTC, merged